
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class StrategicType
 : IConcurrency 
{

    public StrategicType()
    {

        this.ProjectStrategicTypes = new HashSet<ProjectStrategicType>();

    }


    public long StrategicTypeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public System.DateTime Timestamp { get; set; }



    public virtual ICollection<ProjectStrategicType> ProjectStrategicTypes { get; set; }

}

}
