//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPO.Domain.MapicsOrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfg001r.wsbeans.iseries/", ConfigurationName="MapicsOrderService.CFG001RServices")]
    public interface CFG001RServices {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cfg001r.wsbeans.iseries/CFG001RServices/cfg001rRequest", ReplyAction="http://cfg001r.wsbeans.iseries/CFG001RServices/cfg001rResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DPO.Domain.MapicsOrderService.cfg001rResponse cfg001r(DPO.Domain.MapicsOrderService.cfg001rRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cfg001r.wsbeans.iseries/CFG001RServices/cfg001rRequest", ReplyAction="http://cfg001r.wsbeans.iseries/CFG001RServices/cfg001rResponse")]
        System.Threading.Tasks.Task<DPO.Domain.MapicsOrderService.cfg001rResponse> cfg001rAsync(DPO.Domain.MapicsOrderService.cfg001rRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfg001r.wsbeans.iseries/")]
    public partial class cfg001RInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private porderreq pORDERREQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public porderreq PORDERREQ {
            get {
                return this.pORDERREQField;
            }
            set {
                this.pORDERREQField = value;
                this.RaisePropertyChanged("PORDERREQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfg001r.wsbeans.iseries/")]
    public partial class porderreq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int lengthField;
        
        private string stringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string @string {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("string");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfg001r.wsbeans.iseries/")]
    public partial class cfg001RResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private porderreq pORDERREQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public porderreq PORDERREQ {
            get {
                return this.pORDERREQField;
            }
            set {
                this.pORDERREQField = value;
                this.RaisePropertyChanged("PORDERREQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001r", WrapperNamespace="http://cfg001r.wsbeans.iseries/", IsWrapped=true)]
    public partial class cfg001rRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DPO.Domain.MapicsOrderService.cfg001RInput arg0;
        
        public cfg001rRequest() {
        }
        
        public cfg001rRequest(DPO.Domain.MapicsOrderService.cfg001RInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cfg001rResponse", WrapperNamespace="http://cfg001r.wsbeans.iseries/", IsWrapped=true)]
    public partial class cfg001rResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfg001r.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DPO.Domain.MapicsOrderService.cfg001RResult @return;
        
        public cfg001rResponse() {
        }
        
        public cfg001rResponse(DPO.Domain.MapicsOrderService.cfg001RResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CFG001RServicesChannel : DPO.Domain.MapicsOrderService.CFG001RServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFG001RServicesClient : System.ServiceModel.ClientBase<DPO.Domain.MapicsOrderService.CFG001RServices>, DPO.Domain.MapicsOrderService.CFG001RServices {
        
        public CFG001RServicesClient() {
        }
        
        public CFG001RServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFG001RServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFG001RServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFG001RServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DPO.Domain.MapicsOrderService.cfg001rResponse DPO.Domain.MapicsOrderService.CFG001RServices.cfg001r(DPO.Domain.MapicsOrderService.cfg001rRequest request) {
            return base.Channel.cfg001r(request);
        }
        
        public DPO.Domain.MapicsOrderService.cfg001RResult cfg001r(DPO.Domain.MapicsOrderService.cfg001RInput arg0) {
            DPO.Domain.MapicsOrderService.cfg001rRequest inValue = new DPO.Domain.MapicsOrderService.cfg001rRequest();
            inValue.arg0 = arg0;
            DPO.Domain.MapicsOrderService.cfg001rResponse retVal = ((DPO.Domain.MapicsOrderService.CFG001RServices)(this)).cfg001r(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DPO.Domain.MapicsOrderService.cfg001rResponse> DPO.Domain.MapicsOrderService.CFG001RServices.cfg001rAsync(DPO.Domain.MapicsOrderService.cfg001rRequest request) {
            return base.Channel.cfg001rAsync(request);
        }
        
        public System.Threading.Tasks.Task<DPO.Domain.MapicsOrderService.cfg001rResponse> cfg001rAsync(DPO.Domain.MapicsOrderService.cfg001RInput arg0) {
            DPO.Domain.MapicsOrderService.cfg001rRequest inValue = new DPO.Domain.MapicsOrderService.cfg001rRequest();
            inValue.arg0 = arg0;
            return ((DPO.Domain.MapicsOrderService.CFG001RServices)(this)).cfg001rAsync(inValue);
        }
    }
}
