
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class DCMaintenanceConfig
 : IConcurrency 
{

    public byte MaintenanceId { get; set; }

    public string MaintenanceText { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> EndTime { get; set; }

    public Nullable<long> ModifyBy { get; set; }

    public Nullable<System.DateTime> ModifyOn { get; set; }

    public System.DateTime Timestamp { get; set; }

}

}
