
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class EfficiencyType

{

    public EfficiencyType()
    {

        this.OrderItems = new HashSet<OrderItem>();

        this.QuoteItems = new HashSet<QuoteItem>();

    }


    public byte EfficiencyTypeId { get; set; }

    public string Name { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<long> CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<long> ModifiedBy { get; set; }



    public virtual ICollection<OrderItem> OrderItems { get; set; }

    public virtual ICollection<QuoteItem> QuoteItems { get; set; }

}

}
