
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class LmsCourseSession

{

    public long LmsCourseSessionId { get; set; }

    public Nullable<long> LmsCourseId { get; set; }

    public Nullable<long> LmsFacilityId { get; set; }

    public string LmsObjectId { get; set; }

    public string LocatorNumber { get; set; }

    public Nullable<int> AvailableSeats { get; set; }

    public bool Waitlist { get; set; }

    public Nullable<int> DurationInMinutes { get; set; }

    public string Location { get; set; }

    public Nullable<System.DateTime> StartDateTime { get; set; }

    public Nullable<System.DateTime> EndDateTime { get; set; }

    public string Timezone { get; set; }

    public string TimezoneDescription { get; set; }

    public Nullable<int> Seats { get; set; }

    public Nullable<int> CurrentlyRegistered { get; set; }

    public Nullable<int> MaxRegistration { get; set; }

    public Nullable<int> WaitlistSlots { get; set; }



    public virtual LmsFacility LmsFacility { get; set; }

    public virtual LmsCourse LmsCourse { get; set; }

}

}
