
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class LmsFacility

{

    public LmsFacility()
    {

        this.LmsCourseSessions = new HashSet<LmsCourseSession>();

    }


    public long LmsFacilityId { get; set; }

    public string LmsOuId { get; set; }

    public string Name { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string City { get; set; }

    public Nullable<int> StateProvinceId { get; set; }

    public string PostalCode { get; set; }



    public virtual ICollection<LmsCourseSession> LmsCourseSessions { get; set; }

}

}
