
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class OrderAttachmentType

{

    public OrderAttachmentType()
    {

        this.OrderAttachments = new HashSet<OrderAttachment>();

    }


    public byte OrderAttachmentTypeId { get; set; }

    public string OrderAttachmentType1 { get; set; }



    public virtual ICollection<OrderAttachment> OrderAttachments { get; set; }

}

}
