
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DPO.Data
{

using System;
    using System.Collections.Generic;
    using DPO.Common;
    
public partial class OrderExpediteInfo
 : IConcurrency 
{

    public long OrderExpediteInfoId { get; set; }

    public long OrderId { get; set; }

    public string OrderExpediteReasons { get; set; }

    public System.DateTime Timestamp { get; set; }



    public virtual Order Order { get; set; }

}

}
